"""empty message

Revision ID: fd0c9bbb251c
Revises: 4b97ebe398a6
Create Date: 2022-07-04 13:11:20.085430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0c9bbb251c'
down_revision = '4b97ebe398a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre')
    # ### end Alembic commands ###
